### ISSUE TITLE
Done, without errors.

### ISSUE THREAD

**Issue by douglasdeodato** [shepherdwind/grunt-joycss#1]
i am running joycss and appears done without errors but the file are not created, someone know why the files are not created?

thanks

grunt joycss
Running "joycss:dist" (joycss) task

Done, without errors.

my grunfile.

  //joycss ===============================
        var joycss;
        config.joycss = joycss = {};

```
      joycss.dist = {
          joycss: {
            index: {
              //紧凑拼图
              options: { layout: 'close', force8bit: false },
              cwd: 'public/images/min',
              src: ['sass/index.less'],
              dest: 'public/images/sprite'
            },

            detail: {
              //水平布局
              options: { layout: 'horizontal' },
              cwd: 'public/images/min',
              src: ['sass/index.less'],
              dest: 'public/images/sprite'
            }
          }
```

**Comment by shepherdwind** [comment]
Maybe you should try `grunt --debug`, And so you can see more debug information.

Or, you can try joycss command by:

```
$ npm i joycss -g
$ joycss -o public/images/sprite -c public/images/min/sass/index.less
```

Joycss handle image by php with gd2, or java with [joycss.jar](https://github.com/shepherdwind/joycss.jar). So you should have jre or php installed.

**Comment by shepherdwind** [comment]
If you os is mac or linux, you should install pngquant and optipng.

For mac, you can you brew. Linux apt-get or some other package manager.

This project do not change much, and I did not write English doc, very sorry. I had not use image sprite a long time(now, Just base64 or iconfont can work fine), and there is no some other user. 

But, If you want try, I will support at anytime.

**Comment by douglasdeodato** [comment]
hey man, thanks a lot for your help , a friend from Brasil indicate that for me so that reason i am trying.

actually i am using windows with gitbash

that what i got after run the commands you said.

grunt joycss --debug
Running "joycss:dist" (joycss) task
[D] Task source: C:\wamp\www\demo-site\demo-site\node_modules\grunt-joycss\tasks\joycss.js

Done, without errors.

npm i joycss -g && cd
C:\Users\ddeodato\AppData\Roaming\npm\joycss -> C:\Users\ddeodato\AppData\Roaming\npm\node_modules\joycss\bin\joycss
joycss@0.6.6 C:\Users\ddeodato\AppData\Roaming\npm\node_modules\joycss
├── co@3.1.0
├── unyield@0.0.1
├── osenv@0.0.3
├── thunkify@2.1.2
├── co-exec@1.1.0
├── image-size@0.3.5
├── commander@1.1.1 (keypress@0.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── shelljs@0.1.4
├── co-fs@1.2.0 (thunkify@0.0.1, co-from-stream@0.0.0)
├── css@2.2.1 (inherits@2.0.1, urix@0.1.0, source-map-resolve@0.3.1, source-map@0.1.43)
├── less@1.7.5 (mime@1.2.11, graceful-fs@3.0.8, clean-css@2.2.23, source-map@0.1.43, request@2.40.0)
└── gnode@0.1.0 (regenerator@0.6.10)

$ joycss -o public/images/sprite -c public/images/min/sass/index.less
Mon, 09 Nov 2015 13:47:25 GMT joycss:Error!! 需要java环境支持, 请首先安装java虚拟机，需要更多帮助情况
   https://github.com/shepherdwind/joycss/wiki/how-to-install

**Comment by shepherdwind** [comment]
That error mean you need dependency(php or jre). Windows will very hard to install c++ addon, which may need compile c++, I never successed do it. 

I don't know which will more easy for you. I think php will more easy. So, you can have php from [this link](http://windows.php.net/downloads/releases/archives/php-5.3.9-Win32-VC9-x86.msi). 

Then install it, this is the 5.3.x version php. The newest version php I tried, but fail, and also, there is not an msi package for new version. So, If you do not use php, you just install the old php will fine.

After that, you can try if you php install fine.

```
$ php --version
// if this output you php version, mean that you install php cli fine
```

After php cli install, you will work fine, I try it on my compute successfully.

**Comment by douglasdeodato** [comment]
many thanks for the feedback, works fine for me.

thansk a lot.
